import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { HttpService } from '../../services/http/http.service';
import { ApiRoutes } from '../../shared/enums';

@Injectable({
  providedIn: 'root'
})
export class RoomService {
  constructor(private readonly httpService: HttpService) { }

  public getAll(): Observable<any[]> {
    return this.httpService.get<any[]>(ApiRoutes.Room);
  }

  public editById(id: number, payload: any): Observable<any[]> {
    return this.httpService.put<any[]>(`${ApiRoutes.Room}/${id}`, payload);
  }

  public getAllLocal(): any {
    return of([
      {
        id: 1,
        name: '1',
        description: 'some description',
        area: '37.1',
        length: '6610',
        width: '5620',
        floor_number: 3,
        workplaces: [
          {
            id: 1,
            name: '1.1',
            booking_price: 1900,
            description: 'Near the window',
            room_id: 1,
            position: { y: 45, x: 45 },
            bookings: [],
          },
          {
            id: 2,
            name: '1.2',
            booking_price: 1900,
            description: 'wow',
            room_id: 1,
            position: { y: 45, x: 95 },
            bookings: [],
          },
          {
            id: 3,
            name: '1.3',
            booking_price: 1900,
            description: 'Super',
            room_id: 1,
            position: { y: 120, x: 45 },
            bookings: [],
          },
          {
            id: 4,
            name: '1.4',
            booking_price: 1900,
            description: 'Near',
            room_id: 1,
            position: { y: 120, x: 95 },
            bookings: [],
          },
        ],
      },
      {
        id: 2,
        name: '2',
        description: 'description',
        area: '22.3',
        length: '7000',
        width: '3210',
        floor_number: 3,
        workplaces: [
          {
            id: 5,
            name: '2.1',
            booking_price: 2300,
            description: 'So great',
            room_id: 2,
            position: { y: 45, x: 170 },
            bookings: [],
          },
          {
            id: 6,
            name: '2.2',
            booking_price: 2300,
            description: 'Mama Mia',
            room_id: 2,
            position: { y: 120, x: 170 },
            bookings: [],
          },
        ],
      },
      {
        id: 3,
        name: '3',
        description: 'just description',
        area: '18.6',
        length: '6610',
        width: '2810',
        floor_number: 3,
        workplaces: [
          {
            id: 7,
            name: '3.1',
            booking_price: 1900,
            description: 'Good',
            room_id: 3,
            position: { y: 45, x: 242 },
            bookings: [],
          },
          {
            id: 8,
            name: '3.2',
            booking_price: 1900,
            description: 'Perfect',
            room_id: 3,
            position: { y: 120, x: 242 },
            bookings: [],
          },
        ],
      },
      {
        id: 4,
        name: '4',
        description: 'some some description',
        area: '39.8',
        length: '6610',
        width: '6020',
        floor_number: 3,
        workplaces: [
          {
            id: 9,
            name: '4.1',
            booking_price: 2000,
            description: "It's the best",
            room_id: 4,
            position: { y: 45, x: 380 },
            bookings: [],
          },
          {
            id: 10,
            name: '4.2',
            booking_price: 2000,
            description: 'Not bad',
            room_id: 4,
            position: { y: 45, x: 440 },
            bookings: [],
          },
          {
            id: 11,
            name: '4.3',
            booking_price: 2000,
            description: 'Some comment',
            room_id: 4,
            position: { y: 120, x: 380 },
            bookings: [],
          },
          {
            id: 12,
            name: '4.4',
            booking_price: 2000,
            description: 'This is good',
            room_id: 4,
            position: { y: 120, x: 440 },
            bookings: [],
          },
        ],
      },
      {
        id: 5,
        name: '5',
        description: 'some lame description',
        area: '35.7',
        length: '4950',
        width: '6020',
        floor_number: 3,
        workplaces: [
          {
            id: 13,
            name: '5.1',
            booking_price: 2400,
            description: 'Best seller',
            room_id: 5,
            position: { y: 320, x: 310 },
            bookings: [],
          },
          {
            id: 14,
            name: '5.2',
            booking_price: 2400,
            description: 'No comments',
            room_id: 5,
            position: { y: 370, x: 250 },
            bookings: [],
          },
          {
            id: 15,
            name: '5.3',
            booking_price: 2400,
            description: 'kinda bad',
            room_id: 5,
            position: { y: 370, x: 310 },
            bookings: [],
          },
        ],
      },
      {
        id: 6,
        name: '6',
        description: 'some bad description',
        area: '35.1',
        length: '4950',
        width: '6020',
        floor_number: 3,
        workplaces: [
          {
            id: 16,
            name: '6.1',
            booking_price: 2350,
            description: 'With a lot of lights',
            room_id: 6,
            position: { y: 320, x: 380 },
            bookings: [],
          },
          {
            id: 17,
            name: '6.2',
            booking_price: 2350,
            description: 'Fresh',
            room_id: 6,
            position: { y: 370, x: 380 },
            bookings: [],
          },
          {
            id: 18,
            name: '6.3',
            booking_price: 2350,
            description: 'Open space',
            room_id: 6,
            position: { y: 370, x: 440 },
            bookings: [],
          },
        ],
      },
      {
        id: 7,
        name: '7',
        description: 'some great description',
        area: '68.05',
        length: '11436',
        width: '3500',
        floor_number: 3,
        workplaces: [
          {
            id: 19,
            name: '7.1',
            booking_price: 1700,
            description: 'Open space',
            room_id: 7,
            position: { y: 60, x: 555 },
            bookings: [],
          },
          {
            id: 20,
            name: '7.2',
            booking_price: 1700,
            description: 'Open',
            room_id: 7,
            position: { y: 80, x: 660 },
            bookings: [],
          },
          {
            id: 21,
            name: '7.3',
            booking_price: 1700,
            description: 'Wow',
            room_id: 7,
            position: { y: 120, x: 550 },
            bookings: [],
          },
          {
            id: 22,
            name: '7.4',
            booking_price: 1700,
            description: 'Great',
            room_id: 7,
            position: { y: 140, x: 640 },
            bookings: [],
          },
        ],
      },
      {
        id: 8,
        name: '8',
        description: 'some amazing description',
        area: '68.05',
        length: '11436',
        width: '3500',
        floor_number: 3,
        workplaces: [
          {
            id: 23,
            name: '8.1',
            booking_price: 1700,
            description: 'Wow',
            room_id: 8,
            position: { y: 110, x: 770 },
            bookings: [],
          },
          {
            id: 24,
            name: '8.2',
            booking_price: 1700,
            description: 'Great',
            room_id: 8,
            position: { y: 160, x: 850 },
            bookings: [],
          },
          {
            id: 25,
            name: '8.3',
            booking_price: 1700,
            description: 'Open space',
            room_id: 8,
            position: { y: 170, x: 740 },
            bookings: [],
          },
          {
            id: 26,
            name: '8.4',
            booking_price: 1700,
            description: 'Open',
            room_id: 8,
            position: { y: 215, x: 820 },
            bookings: [],
          },
        ],
      },
      {
        id: 9,
        name: '9',
        description: 'some cool description',
        area: '196.2',
        length: '18600',
        width: '15222',
        floor_number: 3,
        workplaces: [
          {
            id: 27,
            name: '9.1',
            booking_price: 1350,
            description: 'Open space',
            room_id: 9,
            position: { y: 475, x: 1105 },
            bookings: [],
          },
          {
            id: 28,
            name: '9.2',
            booking_price: 1350,
            description: 'Open',
            room_id: 9,
            position: { y: 565, x: 1125 },
            bookings: [],
          },
          {
            id: 29,
            name: '9.3',
            booking_price: 1350,
            description: 'Wow',
            room_id: 9,
            position: { y: 650, x: 1140 },
            bookings: [],
          },
          {
            id: 30,
            name: '9.4',
            booking_price: 1350,
            description: 'Wow',
            room_id: 9,
            bookings: [],
            position: { y: 500, x: 1040 },
          },
          {
            id: 31,
            name: '9.5',
            booking_price: 1350,
            description: 'Open space',
            room_id: 9,
            position: { y: 580, x: 1060 },
            bookings: [],
          },
          {
            id: 31,
            name: '9.6',
            booking_price: 1350,
            description: 'Open',
            room_id: 9,
            position: { y: 655, x: 1070 },
            bookings: [],
          },
          {
            id: 32,
            name: '9.7',
            booking_price: 1350,
            description: 'Wow',
            room_id: 9,
            position: { y: 525, x: 970 },
            bookings: [],
          },
          {
            id: 33,
            name: '9.8',
            booking_price: 1350,
            description: 'Great',
            room_id: 9,
            position: { y: 590, x: 990 },
            bookings: [],
          },
          {
            id: 34,
            name: '9.9',
            booking_price: 1350,
            description: 'Open space',
            room_id: 9,
            position: { y: 660, x: 1000 },
            bookings: [],
          },
          {
            id: 35,
            name: '9.10',
            booking_price: 1350,
            description: 'Open',
            room_id: 9,
            position: { y: 555, x: 895 },
            bookings: [],
          },
          {
            id: 36,
            name: '9.11',
            booking_price: 1350,
            description: 'Wow',
            room_id: 9,
            position: { y: 610, x: 915 },
            bookings: [],
          },
          {
            id: 37,
            name: '9.12',
            booking_price: 1350,
            description: 'Great',
            room_id: 9,
            position: { y: 665, x: 920 },
            bookings: [],
          },
          {
            id: 38,
            name: '9.13',
            booking_price: 1350,
            description: 'Open',
            room_id: 9,
            position: { y: 580, x: 822 },
            bookings: [],
          },
          {
            id: 39,
            name: '9.14',
            booking_price: 1350,
            description: 'Wow',
            room_id: 9,
            position: { y: 627, x: 837 },
            bookings: [],
          },
          {
            id: 40,
            name: '9.15',
            booking_price: 1350,
            description: 'Great',
            room_id: 9,
            position: { y: 677, x: 840 },
            bookings: [],
          },
        ],
      },
    ]);
  }

}
